# Copyright (c) 2020 The PIVX developers
name: pivx-zkpm
base: core18
version: 0.0.1
summary:   PIVX Zk Params Wizard
description: |
  PIVX Zk Params Wizard is a GUI app to assist users in downloading the
  Sapling parameters required for the PIVX Core wallet.
grade: devel
confinement: strict

apps:
  zkparamswizard:
    command: desktop-launch $SNAP/bin/ZkParamsWizard
    plugs: [network, network-bind, network-status, unity7, desktop, desktop-legacy, wayland, x11, mir, opengl, home, gsettings, removable-media, screen-inhibit-control, pulseaudio, media-hub]
    environment:
      DISABLE_WAYLAND: 1
      HOME: $SNAP_USER_COMMON

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: [ "FLAVOR=qt5" ]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [ appmenu-qt5 ] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  pivx-zkpw:
    after: [desktop-qt5]
    source: https://github.com/Fuzzbawls/PIVX-ZKPM
    source-type: git
    source-tag: master
    plugin: python
    python-version: python3
    build-packages:
      - curl
      - wget
      - python3-dev
      - python3-pyqt5
      - libxcb-xinerama0
    stage-packages:
      - python3-dev
      - python3-pyqt5
      - libc-bin
      - libxcb-xinerama0
